# yaml-language-server: \$schema=https://json.schemastore.org/bukkit-plugin.json

name: LagX
version: "${version}"
main: com.seristic.lagx.main.LagX
api-version: 1.20
folia-supported: true
author: Seristic
description: An enhanced lag prevention and cleanup plugin optimized for Folia servers
softdepend: [Towny]

commands:
  lagx:
    description: LagX command with entity limiting and villager optimization.
    usage: /<command> [help|ping|tps|ram|gc|info|status|protocol|clear|count|world|unload|stacker|entities|limiter|towny|preset|villagers|reload|warnings]
  lagxperf:
    description: Comprehensive performance analysis command for detailed server metrics.
    usage: /<command> [regions|memory|threads|world|history|full|help]

permissions:
  lagx.*:
    description: Grants all LagX permissions
    default: op
    children:
      lagx.help: true
      lagx.status: true
      lagx.master: true
      lagx.tps: true
      lagx.world: true
      lagx.clear: true
      lagx.unload: true
      lagx.gc: true
      lagx.update: true
      lagx.nochatdelay: true
      lagx.modules: true
      lagx.ram: true
      lagx.protocol: true
      lagx.ping: true
      lagx.entities: true
      lagx.villagers: true
      lagx.towny: true
      lagx.test: true
      lagx.towny.bypass: true
      lagx.reload: true
      lagx.stacker: true
      lagx.warn: true
      lagx.warn.toggle: true
      lagx.admin: true
      lagx.performance: true

  lagx.help:
    description: Gives access to the help command.
    default: op
  lagx.status:
    description: Gives access to the quick status overview command.
    default: op
  lagx.master:
    description: Gives access to the master listing of all performance data from the server.
    default: op
  lagx.tps:
    description: Gives access to view the Ticks Per Second(TPS) of the server.
    default: op
  lagx.world:
    description: View data about a certain world.
    default: op
  lagx.clear:
    description: Allows you to clear all items on the ground or entities in a world.
    default: op
  lagx.unload:
    description: Allows players to unload all chunks in a world.
    default: op
  lagx.gc:
    description: Allows players to run LagX's garbage collector to free RAM.
    default: op
  lagx.update:
    description: Allows LagX to notify a player when an update is downloaded.
    default: op
  lagx.nochatdelay:
    description: Makes a player immune to the chat delay.
    default: op
  lagx.modules:
    description: Allows you to list loaded modules.
    default: op
  lagx.ram:
    description: Allows players to list the RAM available on the server.
    default: op
  lagx.protocol:
    description: Allows players to view/manipulate protocols.
    default: op
  lagx.ping:
    description: Allows a player to view the ping of another player (or thyself)
    default: op
  lagx.entities:
    description: Allows access to entity limiter commands
    default: op
  lagx.villagers:
    description: Allows access to villager optimization commands
    default: op
  lagx.towny:
    description: Allows access to Towny integration commands
    default: op
  lagx.test:
    description: Allows access to test commands for debugging features
    default: op
  lagx.towny.bypass:
    description: Allows bypassing Towny protection checks for entity cleanup
    default: op
  lagx.reload:
    description: Allows reloading the plugin configuration without server restart
    default: op
  lagx.stacker:
    description: Allows access to entity stacker commands
    default: op
  lagx.warn:
    description: Allows receiving protocol warning messages
    default: op
  lagx.warn.toggle:
    description: Allows toggling protocol warnings on/off
    default: op
  lagx.admin:
    description: Designates a user as an admin for LagX
    default: op

  # LagX Enhanced Features
  lagx.status.command:
    description: Allows access to LagX status command
    default: op
  lagx.monitor:
    description: Allows access to LagX monitor command
    default: op
  lagx.worlds:
    description: Allows access to LagX worlds overview command
    default: op
  lagx.performance:
    description: Allows access to LagX performance report command
    default: op

  # New Performance Command Permissions
  lagxperf.use:
    description: Allows basic usage of the performance command
    default: op
  lagxperf.regions:
    description: Allows viewing region-specific performance data
    default: op
  lagxperf.memory:
    description: Allows viewing detailed memory statistics
    default: op
  lagxperf.threads:
    description: Allows viewing thread usage information
    default: op
  lagxperf.world:
    description: Allows viewing world-specific performance data
    default: op
  lagxperf.history:
    description: Allows viewing TPS history and trends
    default: op
  lagxperf.full:
    description: Allows viewing all performance data at once
    default: op
